[workspace]
resolver = "2"

members = [
    "davey",
    "davey-node",
]

[patch.crates-io]
openmls = { git = "https://github.com/Snazzah/openmls.git", rev = "3f237fb29e0d61cedd43223a6d6df1fbc0a042ad" }
openmls_basic_credential = { git = "https://github.com/Snazzah/openmls.git", rev = "3f237fb29e0d61cedd43223a6d6df1fbc0a042ad" }
openmls_rust_crypto = { git = "https://github.com/Snazzah/openmls.git", rev = "3f237fb29e0d61cedd43223a6d6df1fbc0a042ad" }
aes-gcm = { path = "./davey/aes-gcm" }

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1
